# Generated by Django 2.2.4 on 2019-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('empresa', models.CharField(max_length=80, unique=True)),
                ('serie', models.CharField(max_length=50)),
                ('numero', models.DecimalField(decimal_places=4, max_digits=8)),
                ('descricao', models.CharField(max_length=300)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cubagem', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
