# Generated by Django 2.2.4 on 2019-08-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série:')),
                ('numero', models.CharField(max_length=44, null=True, unique=True, verbose_name='Número:')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição/Nome:')),
                ('peso', models.IntegerField(verbose_name='Peso(Kg):')),
                ('cubagem', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cubagem(m³):')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
            options={
                'ordering': ('empresa',),
            },
        ),
    ]
