# Generated by Django 2.2.4 on 2019-08-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_auto_20190817_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
