# Generated by Django 2.2.4 on 2019-08-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_auto_20190829_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa'),
        ),
    ]
