# Generated by Django 2.2.4 on 2019-08-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0003_auto_20190819_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ('empresa',)},
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='modified',
        ),
    ]
