# Generated by Django 2.2.4 on 2019-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0004_auto_20190821_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cubagem',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cubagem(m³):'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição/Nome:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Empresa:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.CharField(max_length=44, null=True, unique=True, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso(Kg):'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Série:'),
        ),
    ]
