# Generated by Django 2.2.4 on 2019-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0005_auto_20190822_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='descricao',
            field=models.TextField(verbose_name='Descrição/Nome:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.CharField(max_length=44, null=True, unique=True, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='peso',
            field=models.IntegerField(verbose_name='Peso(Kg):'),
        ),
    ]
