# Generated by Django 2.2.4 on 2019-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0007_auto_20190827_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição/Nome:'),
        ),
    ]
