# Generated by Django 2.2.4 on 2019-08-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=44, null=True, unique=True, verbose_name='Empresa:')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ:')),
            ],
            options={
                'ordering': ('empresa',),
            },
        ),
    ]
