# Generated by Django 2.2.4 on 2019-08-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=44, null=True, verbose_name='Empresa:'),
        ),
    ]
