# Generated by Django 2.2.4 on 2019-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190822_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=44, null=True, unique=True, verbose_name='Número:'),
        ),
    ]
