# Generated by Django 2.2.4 on 2019-08-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20190827_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=44, null=True, unique=True, verbose_name='Empresa:'),
        ),
    ]
