# Generated by Django 2.2.4 on 2019-08-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20190827_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('empresa',)},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='empresa',
        ),
    ]
